gems:
  - jekyll-sitemap
  - jekyll-paginate
  
title: Life of a Steamed Fish
email: zhengyu.lenny.li@gmail.com
description:
  A collection of my travels, hobbies, and random thoughts.
baseurl: "/steamedfish_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zhengyulennyli
github_username:  zhengyulennyli

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
